### ISSUE TITLE
redesign NEST product logos

### ISSUE THREAD

**Issue by telepath37** [insightsengineering/nest#1]
## Requirements

~~- color palette: #8ecae6 // #219ebc // #023047 // #ffb703 // #fb8500 (https://venngage.com/blog/blue-color-palettes/#3)~~
~~- font: Helvetica~~
- [x] package name: uppercase for NEST, lowercase for all packages (i.e. _**teal**_ rather than TEAL)
- [x] no boarder line or shadow for the hex sticker
- [x] design should be simple but related to the package it represents (e.g. some kind of interactivity shown in the logo for `teal`)
- [x] high resolution (ppi=300 minimum, ideally at 500+)
- [x] sticker size: 1.74” x 2” (this is for printing purposes)

## Scope
We need logos/hex-stickers for:

- [x] NEST
- [x] teal
- [x] rtables
- [x] tern
- [x] rlistings
- [x] chevron
- [x] scda (new)
- [x] TLG-Catalog (optional)
- [x] Biomarker Catalog (optional)
- [x] teal.gallery (optional)

## Logos to be used in:

- All communications
- All presentations/talks
- Website

**Comment by lcd2yyz** [comment]
Is `hermes` `helios` and its teal module companion in our scope? Also the recently established [`biomarker-catalog` ](https://github.com/insightsengineering/biomarker-catalog)

**Comment by shajoezhu** [comment]
better check with @danielinteractive , I thought helios is not open-sourced.

**Comment by danielinteractive** [comment]
Thanks @lcd2yyz and @shajoezhu for asking and thinking of them!

- So `hermes` and `helios` are not part of NEST, therefore not in scope (and we have logos for them already). 
- The corresponding teal modules are part of NEST. Only `teal.modules.hermes` is open sourced - that could go into your scope, if you could align the design with `hermes` as well as other `teal` module designs that could be cool. 
- The `biomarker-catalog` is also a joint venture of NEST and Statistical Engineering and could also be in scope, maybe the design could be aligned with the `tlg-catalog`.

**Comment by telepath37** [comment]
@epijim can you suggest some contacts for creating logos for NEST products? Just curious who/which group created our existing logos and we'd like to update some and add new ones to the list.

**Comment by telepath37** [comment]
@gogonzo I heard you helped design some NEST package hex-stickers. As we are going to use them on our website, we are thinking to re-touch the stickers to make them more consistent in terms of color/theme/etc. Is this something you'd like to take on?

We need to re-touch logos for the following: NEST, teal, rtables, rlistings, tern and maybe consider add 2 more: TLG-Catalog and teal.gallery

Some ideas:
- tern & teal logos have a gray boarder but logo for NEST doesn't, rtables have a white boarder as well as a shade, we need to make them all look consistent (e.g. without boarder or shade)
- use same font, resolution, size for the logos 
- change color theme for rlistings so that it matches with NEST, tern, teal, rtables
- design logos for TLG-Catalog and teal.gallery

**Comment by Melkiades** [comment]
`rtables` design is recent and was already praised as quite effective and nice. We need to change only the color theme there. The same goes with formatters, as I could not think of anything better as a symbol for it. I am quite sure the others should be remade entirely (speaking principally about tern which is a bit old-fashioned). For the color theme discussion I would go here: #4

**Comment by gogonzo** [comment]
Hi @telepath37 I designed NEST logo long time ago, but I wouldn't call myself a graphic designer and I'm really slow with this as I do this very rarely. Two years ago packages logos were designed and it was done by some graphic designer from Genentec - @epijim knows more about this.

**Comment by telepath37** [comment]
To summarize requirements and scope of work:

1. **logos to create/redesign**: NEST, `teal`, `tern`, `chevron`, `rtables`, `rlistings`, `scda` (new)
2. **Requirements**:

    - [ ] color palette: #8ecae6 // #219ebc // #023047 // #ffb703 // #fb8500 (https://venngage.com/blog/blue-color-palettes/#3)
    - [ ] font: Helvetica
    - [ ] package name: uppercase for NEST, lowercase for all packages (i.e. _**teal**_ rather than TEAL)
    - [ ] no boarder line or shadow for the hex sticker
    - [ ] design should be simple but related to the package it represents (e.g. some kind of interactivity shown in the logo for `teal`)
    - [ ] high resolution (ppi=300 minimum, ideally at 500+)
    - [ ] sticker size: 1.74” x 2” (this is for printing purposes)
3. We will consider creating hex-stickers for TLG Catalog, Biomarker Catalog and teal.gallery as well

**Comment by telepath37** [comment]
update: Appsilon will start the designing process (10-20hrs of work, for all stickers listed in the original issue) after the kick off meeting on Aug 2.

**Comment by gogonzo** [comment]
Nice logos and they refer to the initial "nest/bird" related idea. Thanks!
