### ISSUE TITLE
introductory video for NEST

### ISSUE THREAD

**Issue by telepath37** [insightsengineering/nest#2]
The introductory video should give a very high-level overview of the entire NEST project, and should be consistently referred to when introducing NEST to new users, stakeholders and collaborators.

## Key requirements:

- [ ] video should cover: what is NEST, highlight of its key products, transformational impact it brings
- [ ] short & concise, advertisement-like video (i.e. NOT a tutorial/screening recording of demo) - ideally less than 90 seconds
- [ ] in 16x9 or 21x9 aspect ratios

The video will be embedded in the NEST website, and be made available on pharmaverse youtube channel

**Comment by lcd2yyz** [comment]
Additional idea - create a cartoon character as the host or themed "educator" that we can use consistently through the video series (example: Mr. Stick in our internal PDD educational videos). Some not-well-thought-out ideas include baby birdie or Dr. egg (bird egg?) :zany_face:

**Comment by yinmy0503** [comment]
Some idea:
- One sentence to explain data flow to outputs （RAVE + non-eCRF > SDTM > ADAM > TLGs)
- Focus on ADAMs > TLGs: one or two examples of TLGs generated by NEST to demonstrate the advantages(like flexibility, and efficiency ) of using NEST compared to traditional SAS.

**Comment by telepath37** [comment]
Script generated by gpt:

[Background music playing]
[Scene 1: A data scientist working on a complex data analysis project]
Narrator: "In the dynamic world of data science, having the right tools is essential."
[Scene 2: Shots of NEST's interface showcasing its features and functionalities]
Narrator: "Introducing NEST, the ultimate solution for data scientists in the pharmaceutical industry."
[Scene 3: A data scientist collaborating with team members in a virtual meeting]
Narrator: "With NEST, collaboration becomes effortless, enabling your team to work together seamlessly and achieve remarkable results."
[Scene 4: NEST's powerful data management capabilities]
Narrator: "NEST empowers data scientists with robust data management tools, allowing you to organize, analyze, and extract valuable insights from vast amounts of data."
[Scene 5: Data scientists leveraging NEST's advanced analytics and machine learning capabilities]
Narrator: "Unleash the full potential of your data with NEST's advanced analytics and machine learning algorithms, enabling you to uncover hidden patterns and make data-driven decisions."
[Scene 6: NEST's interactive visualization tools and dashboards]
Narrator: "Transform complex data into compelling visualizations and interactive dashboards, making it easier to communicate insights and drive meaningful actions."
[Scene 7: Shots of pharmaceutical researchers working in a lab]
Narrator: "NEST revolutionizes the pharmaceutical industry, fueling breakthroughs in drug discovery and development."
[Scene 8: NEST's secure and compliant infrastructure]
Narrator: "Rest assured, NEST prioritizes the security and compliance of your valuable data, meeting industry standards and regulations."
[Scene 9: Testimonials from satisfied data scientists and pharmaceutical industry professionals]
Narrator: "Join the community of data scientists and pharmaceutical experts who have experienced the transformative power of NEST."
[Scene 10: The NEST logo and tagline appear on the screen]
Narrator: "NEST: Empowering Data Scientists in the Pharmaceutical Industry."
[Scene 11: Contact information and call-to-action]
Narrator: "Visit our website at [www.nestrepository.com](http://www.nestrepository.com/) to explore how NEST can supercharge your data science journey."
[Scene 12: Fade out with the NEST logo]
Narrator: "NEST: Unleash the true potential of your data."
[Backgro

**Comment by Melkiades** [comment]
It is very hard to read for me. Also, I think it feels like a collection of vague taglines (sorry chatgpt). It is also risky to say things like "effortless", and then we know it is already lengthy to install. It could sound like overselling and putting the wrong spin on it. Doing advertising as Duolingo is not the way in my opinion. 

The best way to proceed here is to look at other packages ([by downloads e.g.](https://www.computerworld.com/article/2920117/most-downloaded-r-packages-last-month.html)) and how their intro videos are made. Until now, I did not find any that did not have a presentation. We could do one that is fancy and dynamic like with prezi, but probably is still the best way, also considering who is the target audience (academia and healthcare and mainly R programmers)

**Comment by Melkiades** [comment]
> Regarding audience - I actually hope this video could resonate well with people who have little technical knowledge (e.g. a leader in a pharma company who are new to open-source tools for clinical reporting), and for developers/active R users, we have specific product pages where they can find demos/examples/app gallery.
> 
> As this is a website for NEST rather than for a specific package, I would lean towards building it more for marketing purposes, and technical details could be hidden in the 2nd layer of the site, and in many cases, exist in the pkgdown sites.

I see! It makes sense indeed. I think we need then to go beyond open-source R packages for this kind of video. I just remember a famous analysis software that a friend of mine was using (a non-technical friend of mine) and I found this video: [here](https://www.tableau.com/why-tableau/what-is-tableau#video). Would something like this work? Talking about style, of course, content differs here. Doing some more research about this ^^

**Comment by yinmy0503** [comment]
As a potential end user (Data Scientist) of  NEST myself, I actually like the Matlab video better and think we could do something similar in 30 seconds.
If we want to use this video to attract new users, then we better show some examples that are highly related to users' daily work, ( like standard TLGs in the Shiny app, and how to get subgroup results with a few clicks from the Shiny app), I think both Matlab and Salesforce videos have shown some examples, but Matlab video is more attractive from data programming perspective.

Another attractive point is to show the efficiency of the NEST tool, compared to traditional tools like SAS coding, for example, for a particular KM figure, what we did in SAS (time, process, etc.) VS what we do in NEST.

**Comment by telepath37** [comment]
done - AI-generated video was completed and ready for dissemination. Will embed in website homepage

**Comment by telepath37** [comment]
done - AI-generated video was completed and ready for dissemination. Will embed in website homepage.
