### ISSUE TITLE
NEST web content map

### ISSUE THREAD

**Issue by yinmy0503** [insightsengineering/nest#8]
### Home Page (Main page): 
- Section: Home, Learn, Blog, Contribute, About us 
- Slogan (#5): focus on the impact of NEST and inspire potential users to try it out
-  #9 Introduction:  what is NEST?  The goal is to let the end users (like PD ADS) feel related and want to use NEST for daily clinical report work. 
- 30s video (#2): Marketing and advertising the NEST product so the targeted users would know how NEST could support the daily work and also want to try it.
- Key products (#3): teal, rtables, tern, TLG-C
  - Product description (one or a few sentences introduction) 
  - Links to Product subpages which contain simple examples of each product, helpful links, etc.
- Product/Project Roadmap (high-level)

### Learn Page:
- Training Materials on products (beginner level)
- reach out for help (slack channels, github issues)

### Blog Page:
- upcoming events/presentations
- latest release news (or any general news)

### Contribute Page:
- can follow what tidyverse did: https://www.tidyverse.org/contribute/
- highlight collaborations and how to reach out to collaborate

### About us:
- Contacts: POs, ETLs, list of developers (link to github profile)

**Comment by pawelru** [comment]
I think we need a top-level "Blog" section where we will be posting news about releases or some other learning articles.
Generally speaking I would target into something like https://www.tidyverse.org/. It has a very clear structure

**Comment by telepath37** [comment]
I updated the content map to set up a clear structure of the website

**Comment by khatril** [comment]
Consider splitting out 'Packages' from the home page as a separate page on the website. This will allow us to have high-level info on our home page then we can dedicate a new page to explain our products

**Comment by telepath37** [comment]
consider adding a section for 'testimonials' from users

**Comment by Melkiades** [comment]
> consider adding a section for 'testimonials' from users

Similarly, probably less demanding content-wise is to post the logos of the companies using (i.e. also the collaborations). This would give a very pro vibe about the content. We need approval for this I guess though

**Comment by yinmy0503** [comment]
For Blog Pages: 
1. Who should centrally control the blogs published on this page? Would the product owners be good as central controllers? 
2. Who should be contributors to the blogs and articles? Would it be developers to share new releases, or end users to share some "cheat sheet" of coding and debugging, or both? 

For the Contribution Page, agree that Tidyverse is a good referral example, we can add three types of contributions:
1. Contribute code
2. Contribute documentation
3. Offer help to answer questions

**Comment by telepath37** [comment]
**_Here is the updated content map after consolidating comments from above:_**

Website will be constructed according to this plan. This issue can be closed.

### Home Page (Main page):
- Section: Home, Packages/Products, Learn, Blog, Contribute, About us
- Slogan/Tagline (https://github.com/insightsengineering/nest/issues/5): _Accelerating Clinical Reporting_
- https://github.com/insightsengineering/nest/issues/9 Introduction: what is NEST? The goal is to let the end users (like PD ADS) feel related and want to use NEST for daily clinical report work.
- 30s video (https://github.com/insightsengineering/nest/issues/2): Marketing and advertising the NEST product so the targeted users would know how NEST could support the daily work and also want to try it.
- Latest news: links from the blog page
- Product/Project Roadmap (high-level): maybe a history timeline of the project?
- Product carousel (#3)

### Package/Products Page:
- Key products (https://github.com/insightsengineering/nest/issues/3): teal, rtables, tern, TLG-C
- Product description (one or a few sentences introduction)
- Links to Product subpages (consider linking to pkgdown pages directly)

### Learn Page:
- Training Materials on products (beginner level) - i.e. getting started
- reach out for help (slack channels, github issues)

### Blog Page:
- upcoming events/presentations
- testimonials (from external collaborators, users, etc.)
- latest release news (or any general news)

### Contribute Page:
- can follow what tidyverse did: https://www.tidyverse.org/contribute/ (contribute code, documentation, offer help)
- highlight collaborations and how to reach out to collaborate

### About Us Page:
Contacts: POs, ETLs, list of developers (link to github profile)
